name: Build Pygame Application

# Trigger the workflow on push to main branch and on new releases
on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version
          architecture: 'x64'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Step 4: Build the executable with PyInstaller
      - name: Build Executable
        run: |
          pyinstaller --onefile --noconsole main.py
        # Adjust the PyInstaller command as needed (e.g., add --icon, --add-data)

      # Step 5: Upload the build artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pygame-app-${{ matrix.os }}
          path: |
            dist/main.exe        # Windows executable
            dist/main            # macOS/Linux executable
